# Padronizar nomes das colunas para todos os anos
# Definindo os anos para os quais os arquivos serão processados
anos <- 2007:2023

# Definindo a lista de renomeação de colunas
renomear_colunas <- list(
  "Total.Aprovação.Fundamental" = "aprov_tot_ef",
  "Total.Aprovação.no.Ens..Fundamental" = "aprov_tot_ef",
  "Total.Aprovação.no.Ens..Fundamental" = "aprov_tot_ef",
  "Aprovação.1ª.a.4ª..Série.1º.a.5º.Ano" = "aprov_ai_ef",
  "Aprovação...Anos.Iniciais..1º.ao.5º.Ano." = "aprov_ai_ef",
  "Anos.Iniciais...11" = "aprov_ai_ef",
  "Aprovação.5ª.a.8ª.Série..6º.ao.9º.Ano" = "aprov_af_ef",
  "Aprovação...Anos.Finais..6º.ao.9º.Ano." = "aprov_af_ef",
  "Anos.Finais...12" = "aprov_af_ef",
  "Aprovação.no.1º.Ano.do.Ensino.Fundamental" = "aprov_1o_ano",
  "Aprovação.no.1º.Ano" = "aprov_1o_ano",
  "X1º.Ano...13" = "aprov_1o_ano",
  "Aprovação.na.1ª.série.2º.Ano" = "aprov_2o_ano",
  "Aprovação.no.2º.Ano" = "aprov_2o_ano",
  "X2º.Ano...14" = "aprov_2o_ano",
  "Aprovação.na.2ª.série.3º.Ano" = "aprov_3o_ano",
  "Aprovação.no.3º.Ano" = "aprov_3o_ano",
  "X3º.Ano...15" = "aprov_3o_ano",
  "Aprovação.na.3ª.série.4º.Ano" = "aprov_4o_ano",
  "Aprovação.no.4º.Ano" = "aprov_4o_ano",
  "X4º.Ano...16" = "aprov_4o_ano",
  "Aprovaçãona.4ª.série.5º.Ano" = "aprov_5o_ano",
  "Aprovação.no.5º.Ano" = "aprov_5o_ano",
  "X5º.Ano...17" = "aprov_5o_ano",
  "Aprovação.na.5ª.série.6º.Ano" = "aprov_6o_ano",
  "Aprovação.no.6º.Ano" = "aprov_6o_ano",
  "X6º.Ano...18" = "aprov_6o_ano",
  "Aprovação.na.6ª.série.7º.Ano" = "aprov_7o_ano",
  "Aprovação.no.7º.Ano" = "aprov_7o_ano",
  "X7º.Ano...19" = "aprov_7o_ano",
  "Aprovação.na.7ª.série.8º.Ano" = "aprov_8o_ano",
  "Aprovação.no.8º.Ano" = "aprov_8o_ano",
  "X8º.Ano...20" = "aprov_8o_ano",
  "Aprovação.na.8ª.série.9º.Ano" = "aprov_9o_ano",
  "Aprovação.no.9º.Ano" = "aprov_9o_ano",
  "X9º.Ano...21" = "aprov_9o_ano",
  "Total..Aprovação.Médio" = "aprov_tot_em",
  "Total.Aprovação.no.Ens..Médio" = "aprov_tot_em",
  "Total...22" = "aprov_tot_em",
  "Total..Aprovação.Médio.Não.Seriado" = "aprov_nseriado_em",
  "Aprovação.Médio.Não.Seriado" = "aprov_nseriado_em",
  "Não.Seriado...27" = "aprov_nseriado_em",
  "Aprovação.na.1ª.série...Médio" = "aprov_1a_em",
  "Aprovação.na.1ª.série" = "aprov_1a_em",
  "X1ª.série...23" = "aprov_1a_em",
  "Aprovação.na.2ª.série...Médio" = "aprov_2a_em",
  "Aprovação.na.2ª.série" = "aprov_2a_em",
  "X2ª.série...24" = "aprov_2a_em",
  "Aprovação.na.3ª.série...Médio" = "aprov_3a_em",
  "Aprovação.na.3ª.série" = "aprov_3a_em",
  "X3ª.série...25" = "aprov_3a_em",
  "Aprovação.na.4ª.série...Médio" = "aprov_4a_em",
  "Aprovação.na.4ª.série" = "aprov_4a_em",
  "X4ª.série...26" = "aprov_4a_em",
  "Reprovação.no.1º.Ano.do.Ensino.Fundamental" = "reprov_1o_ano",
  "Reprovação.no.1º.Ano" = "reprov_1o_ano",
  "X1º.Ano...31" = "reprov_1o_ano",
  "Reprovação.na.1ª.série.2º.Ano" = "reprov_2o_ano",
  "Reprovação.no.2º.Ano" = "reprov_2o_ano",
  "X2º.Ano...32" = "reprov_2o_ano",
  "Reprovação.na.2ª.série.3º.Ano" = "reprov_3o_ano",
  "Reprovação.no.3º.Ano" = "reprov_3o_ano",
  "X3º.Ano...33" = "reprov_3o_ano",
  "Reprovação.na.3ª.série.4º.Ano" = "reprov_4o_ano",
  "Reprovação.no.4º.Ano" = "reprov_4o_ano",
  "X4º.Ano...34" = "reprov_4o_ano",
  "Reprovação.na.4ª.série.5º.Ano" = "reprov_5o_ano",
  "Reprovação.no.5º.Ano" = "reprov_5o_ano",
  "X5º.Ano...35" = "reprov_5o_ano",
  "Reprovação.na.5ª.série.6º.Ano" = "reprov_6o_ano",
  "Reprovação.no.6º.Ano" = "reprov_6o_ano",
  "X6º.Ano...36" = "reprov_6o_ano",
  "Reprovação.na.6ª.série.7º.Ano" = "reprov_7o_ano",
  "Reprovação.no.7º.Ano" = "reprov_7o_ano",
  "X7º.Ano...37" = "reprov_7o_ano",
  "Reprovação.na.7ª.série.8º.Ano" = "reprov_8o_ano",
  "Reprovação.no.8º.Ano" = "reprov_8o_ano",
  "X8º.Ano...38" = "reprov_8o_ano",
  "Reprovação.na.8ª.série.9º.Ano" = "reprov_9o_ano",
  "Reprovação.no.9º.Ano" = "reprov_9o_ano",
  "X9º.Ano...39" = "reprov_9o_ano",
  "Reprovação.1ª.a.4ª..Série.1º.a.5º.Ano" = "reprov_ai_ef",
  "Reprovação...Anos.Iniciais..1º.ao.5º.Ano." = "reprov_ai_ef",
  "Anos.Iniciais...29" = "reprov_ai_ef",
  "Reprovação.5ª.a.8ª.Série..6º.ao.9º.Ano" = "reprov_af_ef",
  "Reprovação...Anos.Finais..6º.ao.9º.Ano." = "reprov_af_ef",
  "Anos.Finais...30" = "reprov_af_ef",
  "Total.Reprovação.Fundamental" = "reprov_tot_ef",
  "Total.Reprovação.no.Ens..Fundamental" = "reprov_tot_ef",
  "Total...28" = "reprov_tot_ef",
  "Reprovação.na.1ª.série...Médio" = "reprov_1a_em",
  "Reprovação.na.1ª.série" = "reprov_1a_em",
  "X1ª.série...41" = "reprov_1a_em",
  "Reprovação.na.2ª.série...Médio" = "reprov_2a_em",
  "Reprovação.na.2ª.série" = "reprov_2a_em",
  "X2ª.série...42" = "reprov_2a_em",
  "Reprovação.na.3ª.série...Médio" = "reprov_3a_em",
  "Reprovação.na.3ª.série" = "reprov_3a_em",
  "X3ª.série...43" = "reprov_3a_em",
  "Reprovação.na.4ª.série...Médio" = "reprov_4a_em",
  "Reprovação.na.4ª.série" = "reprov_4a_em",
  "X4ª.série...44" = "reprov_4a_em",
  "Total..Reprovação.Médio.Não.Seriado" = "reprov_nseriado_em",
  "Reprovação.Médio.Não.Seriado" = "reprov_nseriado_em",
  "Não.Seriado...45" = "reprov_nseriado_em",
  "Total..Reprovação.Médio" = "reprov_tot_em",
  "Total.Reprovação.no.Ens..Médio" = "reprov_tot_em",
  "Total...40" = "reprov_tot_em",
  "Abandono.1ª.a.4ª..Série.1º.a.5º.Ano" = "abandono_ai_ef",
  "Abandono...Anos.Iniciais..1º.ao.5º.Ano." = "abandono_ai_ef",
  "Anos.Iniciais...47" = "abandono_ai_ef",
  "Abandono.5ª.a.8ª.Série..6º.ao.9º.Ano" = "abandono_af_ef",
  "Abandono...Anos.Finais..6º.ao.9º.Ano." = "abandono_af_ef",
  "Anos.Finais...48" = "abandono_af_ef",
  "Abandono.no.1º.Ano.do.Ensino.Fundamental" = "abandono_1o_ano",
  "Abandono.no.1º.Ano" = "abandono_1o_ano",
  "X1º.Ano...49" = "abandono_1o_ano",
  "Abandono.na.1ª.série.2º.Ano" = "abandono_2o_ano",
  "Abandono.no.2º.Ano" = "abandono_2o_ano",
  "X2º.Ano...50" = "abandono_2o_ano",
  "Abandono.na.2ª.série.3º.Ano" = "abandono_3o_ano",
  "Abandono.no.3º.Ano" = "abandono_3o_ano",
  "X3º.Ano...51" = "abandono_3o_ano",
  "Abandono.na.3ª.série.4º.Ano" = "abandono_4o_ano",
  "Abandono.no.4º.Ano" = "abandono_4o_ano",
  "X4º.Ano...52" = "abandono_4o_ano",
  "Abandono.na.4ª.série.5º.Ano" = "abandono_5o_ano",
  "Abandono.no.5º.Ano" = "abandono_5o_ano",
  "X5º.Ano...53" = "abandono_5o_ano",
  "Abandono.na.5ª.série.6º.Ano" = "abandono_6o_ano",
  "Abandono.no.6º.Ano" = "abandono_6o_ano",
  "X6º.Ano...54" = "abandono_6o_ano",
  "Abandono.na.6ª.série.7º.Ano" = "abandono_7o_ano",
  "Abandono.no.7º.Ano" = "abandono_7o_ano",
  "X7º.Ano...55" = "abandono_7o_ano",
  "Abandono.na.7ª.série.8º.Ano" = "abandono_8o_ano",
  "Abandono.no.8º.Ano" = "abandono_8o_ano",
  "X8º.Ano...56" = "abandono_8o_ano",
  "Abandono.na.8ª.série.9º.Ano" = "abandono_9o_ano",
  "Abandono.no.9º.Ano" = "abandono_9o_ano",
  "X9º.Ano...57" = "abandono_9o_ano",
  "Total.Abandono.Fundamental" = "abandono_tot_ef",
  "Total.Abandono.Ens..Fundamental" = "abandono_tot_ef",
  "Total...46" = "abandono_tot_ef",
  "Abandono.na.1ª.série...Médio" = "abandono_1a_em",
  "Abandono.na.1ª.série" = "abandono_1a_em",
  "X1ª.série...59" = "abandono_1a_em",
  "Abandono.na.2ª.série...Médio" = "abandono_2a_em",
  "Abandono.na.2ª.série" = "abandono_2a_em",
  "X2ª.série...60" = "abandono_2a_em",
  "Abandono.na.3ª.série...Médio" = "abandono_3a_em",
  "Abandono.na.3ª.série" = "abandono_3a_em",
  "X3ª.série...61" = "abandono_3a_em",
  "Abandono.na.4ª.série...Médio" = "abandono_4a_em",
  "Abandono.na.4ª.série" = "abandono_4a_em",
  "X4ª.série...62" = "abandono_4a_em",
  "Total..Abandono.Médio.Não.Seriado" = "abandono_nseriado_em",
  "Abandono.Médio.Não.Seriado" = "abandono_nseriado_em",
  "Não.Seriado...63" = "abandono_nseriado_em",
  "Total.Abandono...Médio" = "abandono_tot_em",
  "Total.Abandono.no.Ens..Médio" = "abandono_tot_em",
  "Total...58" = "abandono_tot_em"
)

# Loop para processar cada ano
for (ano in anos) {
  # Definindo o caminho do arquivo
  file_path <- paste0("C:/Users/rosan/Downloads/rend_esc_", ano, ".csv")
  
  # Lendo o arquivo CSV
  df <- read.csv(file_path)
  
  # Renomeando as colunas com base no dicionário
  new_names <- names(df)
  for (i in seq_along(new_names)) {
    # Verifica se a coluna atual está no dicionário de renomeação
    if (new_names[i] %in% names(renomear_colunas)) {
      new_names[i] <- renomear_colunas[[new_names[i]]]
    }
  }
  
  # Aplicando os novos nomes ao dataframe
  names(df) <- new_names
  
  # Salvando o dataframe com as colunas renomeadas no mesmo arquivo
  write.csv(df, file_path, row.names = FALSE)
}